### ISSUE TITLE
gitea API difference causing validation error on repo sync

### ISSUE THREAD

**Issue by adasauce** [metroline/metroline#1]
I have deployed the latest version of gitea (v1.12.5) at https://git.with.parts and compared to the API that the implementation metroline enforces from the try.gitea.io deployment, it doesn't contain an "internal" key in the repos response. 

git.with.parts swagger: https://git.with.parts/api/swagger#/user/userCurrentListRepos
gitea swagger: https://try.gitea.io/api/swagger#/user/userCurrentListRepos

Perhaps it would be a good idea to make that field optional in metroline server? It's marked as required here: https://github.com/metroline/metroline/blob/master/src/server/git-servers/gitea/gitea.ts#L45 and causes the initial repo sync to fail.

Logs:
```
server_1       | POST /api/v1/repos/sync 500 180 - 444.055 ms
nginx_1        | 10.8.0.1 - - [28/Oct/2020:14:00:47 -0300] "POST /api/v1/repos/sync HTTP/2.0" 500 180 "https://built.with.parts/" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
server_1       | ValidationError: "[0].internal" is required
```

**Comment by gempain** [comment]
Huh, that's odd, let me check. I'm using Gitea v1.14.0. For sure this can optional as it won't break things. I actually don't understand why they have two different properties. There might be a difference between `public` and `internal`. Let me check real quick and I'll release a new version.

**Comment by adasauce** [comment]
yeah I used to run off the dev releases too until I did a pull and there was a broken DB migration that took me offline for a while.

this is the first time I've run into an API difference like this, and I haven't seen anything in the changelog about a big change about public/internal/private stuff so it must be pretty new.

thanks for taking care of it!

**Comment by gempain** [comment]
Sorry for closing the issue early. I didn't know Github would close it when I merged the PR. I'll reopen until the you can confirm it's fixed on your side.

1.0.2 is building on DockerHub and should be out in the next few minutes. 1, 1.0 and latest will follow but that could take a couple of hours (their builds are super slow).

I also tested setting up a repo to make sure it wouldn't break, and that seems fine. Please let try 1.0.2 and let me know if that works.

**Comment by adasauce** [comment]
just did a docker-compose pull & up, and I've made it to a list of repos!

thanks for the quick turnaround, looks like the fix worked.

**Comment by gempain** [comment]
Very welcome! Thank YOU for taking the time to raise an issue and investigating the issue - was very helpful.
