### ISSUE TITLE
docker hub semver configuration issue

### ISSUE THREAD

**Issue by adasauce** [metroline/metroline#10]
It looks like there's an issue somewhere in the line between the semver release and the docker tagging for this and the metroline-ui repos. It looks like it's injecting an extra period after the minor version.

I didn't see anything in the .metroline.yml or the docker-semver repo either that would have contributed to this at first glance.

https://hub.docker.com/r/metroline/server/tags

![image](https://user-images.githubusercontent.com/60991921/97872490-7d00dc00-1cec-11eb-89cf-90b5645134b3.png)

**Comment by gempain** [comment]
Good catch. I just fixed the config in Docker hub. The next release will be tagged properly. In the meantime you can use the `1.1` or `1` tag which might be a better option. We follow semantic versioning thoroughly so using `1` is safe with us.
