### ISSUE TITLE
change displayed message informing status

### ISSUE THREAD

**Issue by tomaswarynyca** [metroline/metroline#19]
Above we can see the message displayed by drone and below metroline.
The message displayed must be appropriate to the situation.

![image](https://user-images.githubusercontent.com/41587659/109048209-94a60b00-76b5-11eb-98a6-c05ad27f389a.png)

**Comment by gempain** [comment]
Is this in Gitea ? This comes from how format the commit status when calling the Git server. [Here's](https://github.com/metroline/metroline/search?q=COMMIT_STATUS_DESCRPTION) where we set it. Right now, we use a constant `COMMIT_STATUS_DESCRPTION`.

**Comment by tomaswarynyca** [comment]
Yes, I am working in Gitea.
The notification above is from drone.io my current deloys system.
