### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by 12nick12** [metroline/metroline#28]
I was able to get this working behind NGiNX reverse proxy. I had to expose the UI and the server. I was curious if the server is OK to be exposed publicly?

**Comment by gempain** [comment]
@12nick12 hi ! As far as I know it can - and must, since the UI needs to talk to it - be exposed. Runners, however, should not be exposed - even though they're secured.

**Comment by 12nick12** [comment]
OK, thank you. I just wanted to make sure.
