### ISSUE TITLE
Push to Private Docker registry

### ISSUE THREAD

**Issue by 12nick12** [metroline/metroline#29]
I see the documentation [HERE](https://docs.metroline.io/guides/building-docker-images-inside-jobs) for building images, which mentions the docker socket (which since I want to push to my registry I'm assuming I shouldn't have to expose the socket). I would like to use this to push images to my private registry, Pulling from the registry is documented [HERE](https://docs.metroline.io/ci-configuration/private-docker-registry). I was curious of the best way to push an item to private registry using the auth file (config.json). I'm hoping to switch from drone since they were bought.

**Comment by gempain** [comment]
@12nick12 there is currently no way to use a config.json for pushing to a private registry. You will have to use a username and password. So basically, all you need is to configure the socket as explained in the docs (METROLINE_JOB_DOCKER_SOCK), then in your build script:

```
docker build -t my.registry.com/my-image .
docker login -u $USER -p $PASSWORD https://my.registry.com
docker push my.registry.com/my-image .
```

**Comment by 12nick12** [comment]
OK, thank you.

**Comment by gempain** [comment]
Very welcome 😄
