### ISSUE TITLE
repo clone in the metroline container doesn't init submodules

### ISSUE THREAD

**Issue by adasauce** [metroline/metroline#3]
when a pipeline kicks off and the metroline container runs the create-pipeline startup scripts, the clone operation doesn't do anything with submodules.

it looks like the code that kicks that part off is here:

https://github.com/metroline/metroline/blob/master/src/server/pipelines/create-pipeline.ts#L40

```
      `ssh-agent sh -c 'ssh-add ${sshKeyPath}; GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone ${sshUrl} ${REPO_PATH} --quiet'`,
```

I think adding `--recursive` to the `git clone` command should do the job, but I'm not sure what the best way to go about testing this in my deployment would be.

**Comment by gempain** [comment]
Thanks for reporting this issue ! To be honest, I am not familiar with git submodules as it is something I have never used.

Looking at [the docs](https://git-scm.com/book/en/v2/Git-Tools-Submodules), I think a workaround would be to do it manually in a job. Can you try adding the following as **first** job and let me know if that is a good  ?

```
build:
  image: git
  script:
    - git submodule init
    - git submodule update
  dependencies:
    - compute-version
```

I think the option you're mentioning is `--recurse-submodules`. I checked and it seems to work with both repos that have submodules and those that do not, so I'll be more than happy to add it. In the meantime, let me know if the above workaround is good for you.

What do you with "testing this in my deployment would be" ?

**Comment by gempain** [comment]
@adasauce just released 1.1.0, should be fixed now 😄  I'll let you close if that's fixed.

**Comment by adasauce** [comment]
thanks for looking at this, I'll give it a try shortly. IIRC --recursive is an alias for --recurse-submodules so it should work fine.

will follow up soon with results.

**Comment by adasauce** [comment]
hey @gempain , here's what I'm seeing now when I try to do a build.

I see that the metroline deploy key was added to the main repo, but not the other one. since it's a public repo I could switch from the git/ssh uri style for now to https -- but that wouldn't necessarily solve the problem for repos that have submodules that are private repos.

is there somewhere in the UI app where the public key is accessible to import manually into other repo deploy keys? the gitea key manager only shows the fingerprint and not the whole key to import into the other repo.

```
Pulling from metroline/clone
Digest: sha256:753ce8a5fa8ce6b36daff0d3ff80b9aca93c8d266405263c5ce0387a715e0a80
Status: Image is up to date for metroline/clone:next
$ echo -n "$SSH_PRIVATE_KEY" > /tmp/sshkey
$ chmod 600 /tmp/sshkey
$ ssh-agent sh -c 'ssh-add /tmp/sshkey; GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone ssh://git@git.with.parts:2222/cut/cut-contract.git /repo --quiet --recurse-submodules'
Identity added: /tmp/sshkey (/tmp/sshkey)
Warning: Permanently added '[git.with.parts]:2222,[104.37.195.247]:2222' (ECDSA) to the list of known hosts.
Warning: Permanently added '[git.with.parts]:2222,[104.37.195.247]:2222' (ECDSA) to the list of known hosts.

Gitea: Unauthorized
Public (Deploy) Key: 11:metroline deploy key is not authorized to read mirror/openzeppelin-contracts.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'ssh://git@git.with.parts:2222/mirror/openzeppelin-contracts.git' into submodule path '/repo/vendor/openzeppelin-contracts' failed
Failed to clone 'vendor/openzeppelin-contracts'.
```

**Comment by gempain** [comment]
Aww yeah that's unfortunate. I didn't think about authentication. So, the public key is stored in `repo.setup.deployKey.key`. At the moment it's not returned to the UI. This should be changed in [serialize-repo.ts](https://github.com/metroline/metroline/blob/7ecc4b00d5e42a20707c0ab48ee236e70e7c47a1/src/server/repos/serialize-repo.ts#L10) and then displayed in the UI.

I can do this in an hour or so. In the meantime, you can get that key from Mongodb by using a client like Robo3T. 
 Just do:
```
db.getCollection('repos').find({
  name: 'my/repo'
})
```

I actually don't understand why they never show the full public key, because there's just no way to reverse it, so what is the point in hiding it...

Now in the broader picture, we should think about how to fully integrate git submodules when setting up the repo. I don't know whether Gitea (or Gitlab / Github) provide a way to get that information easily via the API. In that case, we could imagine setting up repos automatically when we find submodules. I'm trying to think of the most simple way to do this.

What do you think ?

**Comment by adasauce** [comment]
> I don't know whether Gitea (or Gitlab / Github) provide a way to get that information easily via the API. 

AFAIK this info isn't served via the API. I'd be happy enough even if the build process aborted if it wasn't available to authenticate and indicated in the auth error message that a deploy key had to be manually added for the time being.

I'm not sure what the precedent is for this kind of authentication across the board. I could imagine in a corporate setting, given a private git server, and a self-hosted CI, they would feel comfortable enough to add deploy keys across repos they know are going to need them to do a successful build. It might be a bit presumptuous to prescribe a solution to this through the project, since there are different ways to handle that authentication and they'll have different security considerations on different organizations.

One thing that might help to smooth the process, is to submit an existing private key to the server vs. generated one so people can control access per job with whatever internal process they have to manage their repo security.

All that being said, it seems like a bit of a non-answer to your question. I think it's probably best to either expose the public key in instances where people need to do deeper integration than what is exposed via the git forge, or allow them to supply specific credentials that they know will work for the git repo, and other git / ssh commands executed thereafter.

**Comment by adasauce** [comment]
> db.getCollection('repos').find({
  name: 'my/repo'
})

this worked, btw. I got the deployKey and added it to the other repo.

**Comment by gempain** [comment]
@adasauce awesome, sorry for the delay, been a crazy busy day but I'll update the UI ASAP.

**Comment by adasauce** [comment]
no problem @gempain 

I'll keep an eye open for the changes and test them when you get it. I have a workaround for now though so there's zero urgency from my side.

**Comment by gempain** [comment]
@adasauce just released ui@1.1.0 and server@1.2.0. You'll be able to access it from the repo "gear" dropdown and i'll show up in a modal.

I think automating the submodules setup might be a bit difficult at the moment and will require a few days of thinking, so I think we can leave it as is. If you're happy with this, let me know if the update is good for you, and if so, you can close the issue.

**Comment by adasauce** [comment]
@gempain works for me, thanks! and thanks for all the hard work on this project.

sorry for the reply delay, bust weekend.

I'll add a todo for myself to open a new issue detailing thoughts on submodule handling.

**Comment by gempain** [comment]
Glad the update worked solved your issue for now, and thanks for bearing with us ! I guess it's always the issue when projects start off like this, all sorts of small things to stabilize. I should've started releases with 1.0.0-beta.1 and stay on a beta release train. I'll keep things as is but it's lesson learned 😄 For [Pmbot](https://pmbot.io), we did the same mistake, but now we're on a 2.0.0-beta.X release, so it's a lot easier to keep up with the updates coming out.
