### ISSUE TITLE
How to add DOCKER_AUTH_JSON to global secret

### ISSUE THREAD

**Issue by 12nick12** [metroline/metroline#32]
How do we go about adding DOCKER_AUTH_JSON as a global secret since we'd have to escape json for more json. 

Any chance you guys can provide an example?

**Comment by gempain** [comment]
I think you will have to `JSON.stringify()` it and set a global secret with value `"<one-line-stringified-json-config"`. There might be some hint in #4. You may run into formatting issues.

**Comment by 12nick12** [comment]
OK, and just put that in like as another value? It would be awesome if it could take base64 instead (not a json/node guy, but base64 is easy haha).

**Comment by gempain** [comment]
Yes I think this would work. Let me know if it helps ! Not a JSON guy ? Ah come on, you gotta love JSON !

**Comment by 12nick12** [comment]
I'm slowing coming around. I wasn't a Docker person either until I learned about DroneCI, Authentik, and this.

**Comment by gempain** [comment]
Hm, okay, I though this would work. I'll check tomorrow and let you know how to do it 😄

**Comment by 12nick12** [comment]
Any luck?
