### ISSUE TITLE
Error: Request failed with status code 400 when trying to add secret

### ISSUE THREAD

**Issue by 12nick12** [metroline/metroline#33]
I run my set up behind NGiNX and have the UI and server running with websockets. It was working so not sure why it's not all of the sudden.

**Comment by gempain** [comment]
Hm, I see. Give me a few minutes and I'll release a fix.

**Comment by gempain** [comment]
It's definitely my fault. I broke it yesterday when fixing your previous issues. This will be released in v1.3.2 of the server.

**Comment by 12nick12** [comment]
Awesome, thank you. Sorry for so many requests. This is pretty awesome. 

What's the correct way to update? I've just been running 'docker-compose up --force-recreate --build -d' every so often.

**Comment by gempain** [comment]
No worries 😄  Happy to see that Metroline is getting some love.

To upgrade, simply do this (the docs need some updates):
```
docker-compose pull
docker-compose up -d
```
