### ISSUE TITLE
Docker containers aren't created in appropriate network

### ISSUE THREAD

**Issue by VitSimon** [metroline/metroline#37]
Hello,

I am trying to establish docker stack Gitea - metroline with custom defined network name (cannot use default network - want to host more stacks and need to avoid name collisions).

All the examples I saw and tried are rely on default network without any customization.

I found environment variable in your documentation: https://docs.metroline.io/environment-reference/runner-environment-reference#metroline_docker_options .

When I start pipeline manually, the clone step fails quickly:
![pipeline](https://user-images.githubusercontent.com/89648814/141658030-6802dd43-2ff3-4380-a7fb-8e0a6b8f890e.png)

If I investigate runner container, it seems environment is correctly populated:
![Runner env](https://user-images.githubusercontent.com/89648814/141657722-6f529934-4162-4395-9e0b-9a2ea6d5d0e9.png)

But when I see container which has been created by runner for pipeline, then I see no network mapping is forwarded to it:
![task container 1](https://user-images.githubusercontent.com/89648814/141658105-bf5440a0-5519-4e96-9c28-3df6e73d76b6.png)

![task container 2](https://user-images.githubusercontent.com/89648814/141658147-a8f70115-bc66-4769-b6ea-4516cda69a6c.png)

![task container 3](https://user-images.githubusercontent.com/89648814/141658181-b4cd764a-c6eb-46c5-b4f9-73fa2e67ac74.png)

After some investigation I found processing of variable read is here: [Env runner](https://github.com/metroline/metroline/blob/master/src/runner/env.ts)

My current docker-compose line:
METROLINE_DOCKER_OPTIONS: '{ "HostConfig": { "AutoRemove": true, "NetworkMode": "${NETWORK_NAME}" } }'

tried also:
METROLINE_DOCKER_OPTIONS: ' "HostConfig": { "AutoRemove": true, "NetworkMode": "${NETWORK_NAME}" } ' - failing
METROLINE_DOCKER_OPTIONS: '{ "socketPath": "/var/run/docker.sock", "HostConfig": { "AutoRemove": true, "NetworkMode": "${NETWORK_NAME}" } }' ... has not been worked for me

Single quotes and double quotes are swapped in my file in compare to your documentation. I needed to do it for this:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#json.parse_does_not_allow_single_quotes . Runner fallen to JSON parse format error.

Does there is any solution?

Does it is a bug in metroline or in some 3rd party library?

Thanks in advance for advice.

**Comment by VitSimon** [comment]
Another attachments:
https://github.com/VitSimon/IssueAttachments/tree/master/metroline-37

**Comment by VitSimon** [comment]
Another attachments: full listing of docker-compose
https://github.com/VitSimon/IssueAttachments/tree/master/metroline-37

**Comment by VitSimon** [comment]
My further investigation led me here:
https://github.com/metroline/metroline/blob/1e8a1d8f1681b99e471c2adcd5b3a27ef3bbf24d/src/runner/docker/create-container.ts#L32

**Comment by VitSimon** [comment]
Mistake on my part ... I had wrongly configured SSH module on in Gitea config.
Docker clone image see on git even not in the same network.
Despite of it ... Is it possible to define target docker network for step image?

**Comment by gempain** [comment]
Hi @VitSimon, I think @pimartin can help on this one.

**Comment by VitSimon** [comment]
@gempain : Hi, thanks for dispatching me. I just tried the same steps on other repository and unfortunately i fall to another fault:

git@192.168.0.105: Permission denied (publickey).

Its strange, both of repositories saw for me to be configured correctly from metroline. Both got webhook and deploy key to gitea via metroline so on 1st sight they are almost the same (same user, other hashes for each of repos).

while one of test repos works fine:
![obrazek](https://user-images.githubusercontent.com/89648814/143780046-7bed85d8-d1cb-49a4-ae49-8690b7550e0f.png)

another one later time created failing:
![obrazek](https://user-images.githubusercontent.com/89648814/143780057-45fdd29d-9c8c-4d94-973b-29768167e971.png)

**Comment by VitSimon** [comment]
It seems its another fault done by my tests. I recreated containers probably and due to it my keys were lost probably. I created fully new instances from scratch and it didnt reappear.

**Comment by gempain** [comment]
Happy to see that you were able to resolve your problems ! Very strange behavior 🤔
