### ISSUE TITLE
Docs not working

### ISSUE THREAD

**Issue by csrednicki** [metroline/metroline#39]
Hi, https://docs.metroline.io/ is not working

**Comment by MineLPPhynix** [comment]
the link brings me to a Avira themed phishing attack, which actually is a seemingly genuine Add by Avira wtf
that's so unprofessional, making a Add that completely looks like every scam/phishing attack

**Comment by 12nick12** [comment]
I think this project is dead :-(

**Comment by MineLPPhynix** [comment]
pretty sure there is nothing that says more "this repo is dead" than the last commit almost a year ago where a running demo application was removed

**Comment by gempain** [comment]
> Hi, https://docs.metroline.io/ is not working

@csrednicki thanks for reporting. The metroline.io domain has not been renewed this year, and the demo VPS has been shutdown as we have slowly shifted to using Github Actions for most of our projects.

I will redeploy the docs on Netlify and update the README files to avoid future confusion, once I have a bit of time on my hands.

> the link brings me to a Avira themed phishing attack, which actually is a seemingly genuine Add by Avira wtf that's so unprofessional, making a Add that completely looks like every scam/phishing attack

@MineLPPhynix I think you are right, the metroline.io domain seems to have been purchased by scammers.

> I think this project is dead :-(
> pretty sure there is nothing that says more "this repo is dead" than the last commit almost a year ago where a running demo application was removed

Dead is a strong word. Not actively maintained is probably a better phrasing. I want you to realize that this project - and others on Github - is published for free, maintained and developed for free on our free time, and is free of use as well. You are free to contribute as much as you want. Life happens for all of us, and priorities change. Owning a .io domain and paying for a VPS all year long is an expense that we have decided to cut on as not having them does not prevent this project from living here on Github.

**Comment by gempain** [comment]
@csrednicki I have updated the docs today. We're now using Docusaurus as framework, and the docs are now published using Github Pages at this address: https://metroline.github.io/metroline-docs/

Feel free to improve them!

**Comment by FlorianDevP** [comment]
Thanks, looks great!
