### ISSUE TITLE
Can't seem to configure docker private registry auth

### ISSUE THREAD

**Issue by adasauce** [metroline/metroline#4]
I've been trying on and off all day to massage it into working.

I've been struggling with both some YAML formatting issues with the variable substitution, and having it work once that is working (as far as I can tell).

Through some console log insertions, I'm seeing that even after the JSON gets registered without crashing, something is still ignoring the value along the line.

I can see the secret in the environment being passed around (I've tried both un/pw and token copied from my local `~/.docker/config.json`):
```
DOCKER_AUTH_JSON: '{"auths":{"images.domain.tld":{"username":"un","password":"pw"}}}'
```

but the actual job has no `dockerAuth` field which is needed here: https://github.com/metroline/metroline/blob/7ecc4b00d5e42a20707c0ab48ee236e70e7c47a1/src/runner/jobs/exec-job.ts#L82 to load pass it into the container. It actually logs as `undefined`.

A search through the repo for `dockerAuth` only shows the type definition and the attempt to read it out in exec-job, so I'm guessing there's supposed to be something on the server side setting it when the job is defined maybe? At a bit of a loss debugging it further, but wanted to try to solve it myself first.

**Comment by gempain** [comment]
> I've been trying on and off all day to massage it into working.

I am so sorry ! Please don't wait for the frustration to build up before opening an issue here 😄 I'm very active so you're probably looking for an answer within less than a couple of hours, even on weekends or when I'm on vacation. I'm always happy to help. I think we should have a Slack channel or something where I can help live.

> I've been struggling with both some YAML formatting issues with the variable substitution, and having it work once that is working (as far as I can tell).

Did you figure it out ? What did you struggle with ? Is there a way we could improve configuration to make it easier for people ?

> Through some console log insertions, I'm seeing that even after the JSON gets registered without crashing, something is still ignoring the value along the line.
> 
> I can see the secret in the environment being passed around (I've tried both un/pw and token copied from my local `~/.docker/config.json`):
> 
> ```
> DOCKER_AUTH_JSON: '{"auths":{"images.domain.tld":{"username":"un","password":"pw"}}}'
> ```
> 
> but the actual job has no `dockerAuth` field which is needed here:
> 
> https://github.com/metroline/metroline/blob/7ecc4b00d5e42a20707c0ab48ee236e70e7c47a1/src/runner/jobs/exec-job.ts#L82
> 
> to load pass it into the container. It actually logs as `undefined`.
> A search through the repo for `dockerAuth` only shows the type definition and the attempt to read it out in exec-job, so I'm guessing there's supposed to be something on the server side setting it when the job is defined maybe? At a bit of a loss debugging it further, but wanted to try to solve it myself first.

I appreciate the efforts you put into debugging this, you've actually spotted the problem. I looked at the code and... it's quite embarrassing ... I actually forgot to pass the auth config when creating the job in [`process-ci-config.ts`](https://github.com/metroline/metroline/blob/master/src/server/ci-config/process-ci-config.ts).

I'll fix this first thing in the morning. Greatest apologies for the inconvenience and time you've lost today.

**Comment by adasauce** [comment]
A slack or matrix channel would be a boon, I hate to open tickets to just ask a little question or have a chat about something.

I tried to use this as an exercise to learn more about the project when figuring it out.

regarding the YAML formatting issues, the example from the docs didn't work because of, as far as I can tell, it complaining about spaces. I forced around it by removing all indentation and spaces around the JSON and wrapping it in single quotes.

in my `.metroline.yml`:
```
docker:
  auth: '{{DOCKER_AUTH_JSON}}'
```

I was also able to get it to work like this with an actual formatted JSON.

```
docker:
  auth: |
{{DOCKER_AUTH_JSON}}
jobs: ...
```

but note that I had to push it all the way to the left, and in the secret entry I needed to make sure it would be indented to a string that fit properly in order for the YAML compiler to not complain when it was loading.


one of the parts that made diagnosing the problem more difficult was that I had to trigger a build and get to the second stage after the metroline runner container finished checking out the repo before I knew whether the yaml was going to compile properly with the substitution, and the error returned only gave the error message without the normal yaml compiler context showing what it's complaining about. As in it would only print `All collection items must start at the same column` above the container output area and exit. I assumed it was related to the yaml and secret substitution because it sounded like a yaml error, then more trial and error got the error to go away.

**Comment by gempain** [comment]
@adasauce should be fixed in v1.2.1. Should be available on Dockerhub soon.

As for the secret injection, the docs is wrong. You worked it out right. Another way, probably more simple, would be to convert your docker auth to a single line and do this:

```yaml
docker:
  auth: '{{DOCKER_AUTH_JSON}}'
```

I'd like to get your opinion on how we can improve this, because I still think it can be useful for users to not have to one-line their auth object. Unfortunately, automatically trying to format the injected secret is almost impossible. We could provide a checkbox when adding secrets to convert to a single line the pasted content, that'd be cool, what do you think ? I can add a hint explaining why it's useful.

I'll work on a Slack channel.

**Comment by adasauce** [comment]
I think the checkbox solutions is ideal! I'm sure there could be other instances where it would be useful for secret sharing as well. It would be even nicer if the newline and space stripping was done pre-injection vs. done at submission time so it would be easier to modify and manage the variables if you need to change them at any time down the road instead of parsing a large inline json object to find the right place to put your changes.

thanks for the update. I hope to be able to contribute more down the road so I'm not bugging you for fixes on everything. Your helpfulness is definitely appreciated, and I don't want to wear out my welcome. great work so far :)

**Comment by gempain** [comment]
> I think the checkbox solutions is ideal! I'm sure there could be other instances where it would be useful for secret sharing as well. It would be even nicer if the newline and space stripping was done pre-injection vs. done at submission time so it would be easier to modify and manage the variables if you need to change them at any time down the road instead of parsing a large inline json object to find the right place to put your changes.

Even better than what I suggested ! This is exactly why we came to open source 😄  So, let's do this. I'll add a checkbox saying "one-line at injection" or something similar, and we will inline it at injection time only in the server. Perfect balance, thanks for the suggestion.

> thanks for the update. I hope to be able to contribute more down the road so I'm not bugging you for fixes on everything. Your helpfulness is definitely appreciated, and I don't want to wear out my welcome. great work so far :)

Very welcome. Don't worry at all, I am very thankful that you take the time to report issues, and I'm sorry if any more arise. The test coverage of this project is very low as is and I know it's something we have to improve (it's even mentioned in our README). I am actually honored that sometime gets interested at our work and spends time using it, so thank to you, again.

**Comment by adasauce** [comment]
confirmed fixed in latest.
