### ISSUE TITLE
Create public discussion channel

### ISSUE THREAD

**Issue by gempain** [metroline/metroline#9]
It'd be nice to have a live chat channel where we can talk about Metroline (#4).

**Comment by vsile** [comment]
How about Telegram Group or Channel?
You are welcome to use
https://t.me/metrolines - channel (sorry, metroline is busy)
https://t.me/metrolinechat - chat

**Comment by gempain** [comment]
@vsile thanks for suggesting Telegram. We've started to use Discord on our public projects as Slack isn't offering the features we want at the moment. I've updated the README with a link to the Discord invite. You are welcome to join but as the holidays are approaching we might not be around as usual.

**Comment by tomaswarynyca** [comment]
Hi, it seems that the discord is not working as expected. 
It seems to me that it is not being squeezed as it should, you can implement that all notifications from the repo reach a channel.
If not the other is to use telegram for casual discussions.
